# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "ahci" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-8baf0c40-d7b8-4934-ad7d-44e4e64abaa1";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-8baf0c40-d7b8-4934-ad7d-44e4e64abaa1".device = "/dev/disk/by-uuid/8baf0c40-d7b8-4934-ad7d-44e4e64abaa1";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/50E7-4018";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # boot.kernelModules = [
  #   "acpi_pad"
  #   "aesni_intel"
  #   "af_packet"
  #   "ahci"
  #   "amd_3d_vcache"
  #   "amd_atl"
  #   "amdgpu"
  #   "amdxcp"
  #   "asn1_encoder"
  #   "atkbd"
  #   "autofs4"
  #   "button"
  #   "ccp"
  #   "cec"
  #   "cfg80211"
  #   "configfs"
  #   "crc16"
  #   "dax"
  #   "dm_crypt"
  #   "dmi_sysfs"
  #   "dm_mod"
  #   "drm_buddy"
  #   "drm_display_helper"
  #   "drm_exec"
  #   "drm_panel_backlight_quirks"
  #   "drm_suballoc_helper"
  #   "drm_ttm_helper"
  #   "edac_core"
  #   "edac_mce_amd"
  #   "efi_pstore"
  #   "efivarfs"
  #   "encrypted_keys"
  #   "evdev"
  #   "ext4"
  #   "fat"
  #   "fixed_phy"
  #   "fuse"
  #   "fwnode_mdio"
  #   "ghash_clmulni_intel"
  #   "gpio_amdpt"
  #   "gpio_generic"
  #   "gpu_sched"
  #   "hid"
  #   "hid_generic"
  #   "hid_multitouch"
  #   "hkdf"
  #   "i2c_algo_bit"
  #   "i2c_piix4"
  #   "i2c_smbus"
  #   "inet_diag"
  #   "input_leds"
  #   "intel_rapl_common"
  #   "intel_rapl_msr"
  #   "irqbypass"
  #   "jbd2"
  #   "joydev"
  #   "k10temp"
  #   "kvm"
  #   "kvm_amd"
  #   "led_class"
  #   "libahci"
  #   "libata"
  #   "libphy"
  #   "libps2"
  #   "loop"
  #   "mac_hid"
  #   "mbcache"
  #   "mdio_bus"
  #   "mdio_devres"
  #   "mousedev"
  #   "nf_conntrack"
  #   "nf_defrag_ipv4"
  #   "nf_defrag_ipv6"
  #   "nf_log_syslog"
  #   "nfnetlink"
  #   "nfnetlink_log"
  #   "nfnetlink_queue"
  #   "nf_tables"
  #   "nft_ct"
  #   "nft_fib"
  #   "nft_fib_inet"
  #   "nft_fib_ipv4"
  #   "nft_fib_ipv6"
  #   "nft_log"
  #   "nls_cp437"
  #   "nls_iso8859_1"
  #   "nvme"
  #   "nvme_auth"
  #   "nvme_core"
  #   "nvme_keyring"
  #   "of_mdio"
  #   "onboard_usb_dev"
  #   "overlay"
  #   "qrtr"
  #   "r8169"
  #   "rapl"
  #   "realtek"
  #   "rfkill"
  #   "rng_core"
  #   "rtc_cmos"
  #   "sch_fq_codel"
  #   "scsi_common"
  #   "scsi_mod"
  #   "sd_mod"
  #   "serio"
  #   "sha1"
  #   "snd"
  #   "snd_hda_codec"
  #   "snd_hda_codec_alc882"
  #   "snd_hda_codec_atihdmi"
  #   "snd_hda_codec_generic"
  #   "snd_hda_codec_hdmi"
  #   "snd_hda_codec_realtek_lib"
  #   "snd_hda_core"
  #   "snd_hda_intel"
  #   "snd_hrtimer"
  #   "snd_hwdep"
  #   "snd_intel_dspcfg"
  #   "snd_intel_sdw_acpi"
  #   "snd_pcm"
  #   "snd_seq"
  #   "snd_seq_device"
  #   "snd_seq_dummy"
  #   "snd_timer"
  #   "soundcore"
  #   "sp5100_tco"
  #   "spd5118"
  #   "tcp_diag"
  #   "tee"
  #   "thunderbolt"
  #   "tiny_power_button"
  #   "tpm"
  #   "tpm_crb"
  #   "tpm_tis"
  #   "tpm_tis_core"
  #   "trusted"
  #   "ttm"
  #   "tun"
  #   "uas"
  #   "udp_diag"
  #   "uinput"
  #   "usbhid"
  #   "usb_storage"
  #   "vfat"
  #   "video"
  #   "vivaldi_fmap"
  #   "watchdog"
  #   "wmi"
  #   "wmi_bmof"
  #   "xhci_hcd"
  #   "xhci_pci"
  # ];
}
