# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "ahci" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-8baf0c40-d7b8-4934-ad7d-44e4e64abaa1";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-8baf0c40-d7b8-4934-ad7d-44e4e64abaa1".device = "/dev/disk/by-uuid/8baf0c40-d7b8-4934-ad7d-44e4e64abaa1";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/50E7-4018";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
