# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ohci_pci" "ehci_pci" "virtio_pci" "ahci" "usbhid" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/91350565-93a4-418f-b905-e1fd98d79fe2";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/989E-9895";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  boot.kernelModules = [
    "9pnet"
    "9pnet_virtio"
    "aesni_intel"
    "ahci"
    "atkbd"
    "autofs4"
    "button"
    "ccp"
    "cdrom"
    "chacha_x86_64"
    "configfs"
    "crc16"
    "crc32c_generic"
    "crc32c_intel"
    "crc32_pclmul"
    "crct10dif_pclmul"
    "cryptd"
    "crypto_simd"
    "curve25519_x86_64"
    "dax"
    "dmi_sysfs"
    "dm_mod"
    "edac_core"
    "efi_pstore"
    "efivarfs"
    "ehci_hcd"
    "ehci_pci"
    "evdev"
    "ext4"
    "failover"
    "fat"
    "fuse"
    "gf128mul"
    "ghash_clmulni_intel"
    "hid"
    "hid_generic"
    "i2c_i801"
    "i2c_mux"
    "i2c_smbus"
    "i8042"
    "input_leds"
    "intel_agp"
    "intel_gtt"
    "intel_pmc_bxt"
    "intel_rapl_common"
    "intel_rapl_msr"
    "ip6_udp_tunnel"
    "irqbypass"
    "iTCO_wdt"
    "jbd2"
    "joydev"
    "kvm"
    "kvm_amd"
    "led_class"
    "libahci"
    "libata"
    "libchacha"
    "libchacha20poly1305"
    "libcrc32c"
    "libcurve25519_generic"
    "libps2"
    "loop"
    "lpc_ich"
    "mac_hid"
    "mbcache"
    "mousedev"
    "net_failover"
    "netfs"
    "nf_conntrack"
    "nf_defrag_ipv4"
    "nf_defrag_ipv6"
    "nf_log_syslog"
    "nfnetlink"
    "nf_tables"
    "nft_ct"
    "nft_fib"
    "nft_fib_inet"
    "nft_fib_ipv4"
    "nft_fib_ipv6"
    "nft_log"
    "nls_cp437"
    "nls_iso8859_1"
    "ohci_hcd"
    "ohci_pci"
    "parport"
    "parport_pc"
    "poly1305_x86_64"
    "polyval_clmulni"
    "polyval_generic"
    "ppdev"
    "psmouse"
    "qemu_fw_cfg"
    "qrtr"
    "rfkill"
    "rng_core"
    "rtc_cmos"
    "sch_fq_codel"
    "scsi_common"
    "scsi_mod"
    "serio"
    "serio_raw"
    "sha1_ssse3"
    "sha256_ssse3"
    "sha512_ssse3"
    "snd"
    "snd_hda_codec"
    "snd_hda_codec_generic"
    "snd_hda_core"
    "snd_hda_intel"
    "snd_hrtimer"
    "snd_hwdep"
    "snd_intel_dspcfg"
    "snd_intel_sdw_acpi"
    "snd_pcm"
    "snd_seq"
    "snd_seq_device"
    "snd_seq_dummy"
    "snd_timer"
    "soundcore"
    "sr_mod"
    "tiny_power_button"
    "udp_tunnel"
    "usbhid"
    "vfat"
    "virtio"
    "virtio_balloon"
    "virtio_blk"
    "virtio_console"
    "virtio_dma_buf"
    "virtiofs"
    "virtio_gpu"
    "virtio_net"
    "virtio_pci"
    "virtio_pci_legacy_dev"
    "virtio_pci_modern_dev"
    "virtio_ring"
    "virtio_rng"
    "vivaldi_fmap"
    "vmw_vsock_virtio_transport"
    "vmw_vsock_virtio_transport_common"
    "vsock"
    "watchdog"
    "wireguard"
    "xhci_hcd"
    "xhci_pci"
  ];
}
